teleop_twist_joy:
  axis_linear: 
    x: 1
    y: 0
  scale_linear: 
    x: 0.75
    y: 0.75
  scale_linear_turbo: 3.0
  axis_angular: 2
  scale_angular: 0.25
  scale_angular_turbo: 0.5
  enable_button: 0
  enable_turbo_button: 2
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
